### PR TITLE
os/2 support, and an update for windows

### PR DESCRIPTION
**Pull request by sezero**

### CODE REVIEW

**Comment by psi29a** [comment]
Looks like the previous PR broke windows builds, its trying to link against unsf.dll but it's likely called somehting else now...

Thank you for os/2 support. I was thinking of getting this merged into WildMIDI itself. What do you think? Keep it separated?

**Comment by sezero** [comment]
> Looks like the previous PR broke windows builds, its trying
> to link against unsf.dll but it's likely called somehting else now..

It is possibly building libunsf.dll instead of unsf.dll. MinGW build is
broken too, because CMake'ry is stupidly assuming WIN32==MSVC,
and even if I correct that, unsf.exe build fails with the same error
about unsf.dll: it actually builds libunsf.dll

> Thank you for os/2 support

You're welcome

> I was thinking of getting this merged into WildMIDI itself. What
> do you think? Keep it separated?

I think that will add more bloat to wildmidi, and wildmidi has its own
share of bugs, so my humble suggesting would be avoiding further
crowd in there.

**Comment by psi29a** [comment]
Roger that! Can you add an entry to the changelog for 1.1 please?

I'm wondering if we can't get OS2 / wacom build via a docker container? That's something we can do via Travis-CI I think. What do you think?

**Comment by sezero** [comment]
> Can you add an entry to the changelog for 1.1 please?

Done: PR #22

> I'm wondering if we can't get OS2 / wacom build via a docker container?
> That's something we can do via Travis-CI I think. What do you think?

I have zero experience with Travis and docker, so I can't help with that.

**Pull request merged**
