### PR TITLE
1.1

### PR DESCRIPTION
**Pull request by zvezdochiot**
Library libunsf

### CODE REVIEW

**Comment by psi29a** [comment]
Thanks!

**Comment by sezero** [comment]
Why was renaming the exe from unsf to sf2pat necessary??

**Comment by zvezdochiot** [comment]
The creation of a utility unsf and a library unsf in Cmake is problematic. Plus a more understandable name for such utilities.

**Comment by psi29a** [comment]
you have wildmidi and libwildmidi, same here unsf and libunsf... what's the problem?

**Comment by zvezdochiot** [comment]
Thanks for the prompt. I use it in libmodjpeg. But not in this case. Here, this is not necessary.

**Comment by zvezdochiot** [comment]
>you have wildmidi and libwildmidi

libWildMidi.so (not libwildmidi.so) and wildmidi

Are there other recipes?

**Comment by sezero** [comment]
See PR #23: it builds just fine with unsf and libunsf names with the updated cmake'ry.

**Pull request merged**
