### PR TITLE
add cmake and pkg-config files

### PR DESCRIPTION
**Pull request by psi29a**
basic cmake file to make CLion happy (and working fully).  include pkg-config as well.

### CODE REVIEW

**Comment by sezero** [comment]
- There is no newline at the end of CMakeLists.txt
- The mysterious PKG_CONFIG_REQUIRES, PKG_CONFIG_LIBS and PKG_CONFIG_CFLAGS
  should die, along with the unnecessary 'Requiries:' field in unsf.pc
- Libs.private: -lm needs adding to unsf.pc
- The cflags are missing, such as UNSF_BUILD, UNSF_STATIC, as well as symbol visibility stuff
  like SYM_VISIBILITY, DLL_EXPORT, etc
- Support for elf/macho symbol visibility is missing, as well as support for building as a shared lib
- Running cmake within the source directory will overwite the default makefile:
  The default Makefile needs renaming to Makefile.linux or Makefile.unix or something
- Support for windows, osx are missing

Maybe more..

**Comment by psi29a** [comment]
hahaha... yes, there are. ;)  I just wanted the thing to build.  It is fine enough for my purposes. Now, the question... do we want to build it out or leave it barebones?

**Comment by sezero** [comment]
> do we want to build it out or leave it barebones?

Sorry, can you explain?

**Comment by psi29a** [comment]
You said previously that you didn't want to see cmake in this project. I need cmake so that I can take advantage of CLion (IDE), so I made this barebone cmake file. I'm happy leaving things to the Makefiles for release.

The question is, do we leave it as-is or do we build it out to replace our Makefiles?

**Comment by sezero** [comment]
> You said previously that you didn't want to see cmake in this project.

Mine is just a preference

> need cmake so that I can take advantage of CLion (IDE), so I made this
> barebone cmake file. I'm happy leaving things to the Makefiles for release.
> 
> The question is, do we leave it as-is or do we build it out to replace our
> Makefiles?

We can keep the individual makefiles and cmake side by side.
(You only need to rename the 'Makefile' to e.g. 'Makefile.linux' )

**Comment by psi29a** [comment]
OK :)

**Comment by sezero** [comment]
The individual Makefile still need renaming.  (and the rest of the issues are still there too.)

**Pull request merged**
