### PR TITLE
msvc support

### PR DESCRIPTION
**Pull request by sezero**

### CODE REVIEW

**Comment by sezero** [comment]
There are FIXME notes added: I think we should add system dependent mkdir etc so that access and stat mode macros shouldn't be needed at all. It builds fine for now, but it's ugly..

**Comment by psi29a** [comment]
Nice work, we can now try to get appveyor producing builds for us. :)

Do you think it is necessary to make this a cmake project? To get away from maintaining all the build solutions/makefiles ourselves?

**Comment by sezero** [comment]
On 9/6/16, Bret Curtis notifications@github.com wrote:

> Do you think it is necessary to make this a cmake project?

God, I hope not.  I am happy with the simplicity myself.
But of course it's yours to decide.

> To get away from
> maintaining all the build solutions/makefiles ourselves?

**Comment by psi29a** [comment]
Well, I love CLion, but it requires cmake... thinking of making a barebones cmake profile. It can co-exists with the make files.

**Pull request merged**
