### PR TITLE
1.1.0

### PR DESCRIPTION
**Pull request by zvezdochiot**
Strip CMakeLists.txt

### CODE REVIEW

**Comment by psi29a** [comment]
What is the goal here?

**Comment by zvezdochiot** [comment]
Goal: simplify CMakeLists.txt

This is necessary to solve small problems. Now cmake does not create a reference to libunsf.so.1.1.0. It will be difficult to find a solution in the mess.

**Comment by psi29a** [comment]
It looks at first glance, @sezero cast your eye here please since you last worked on this please.

**Comment by zvezdochiot** [comment]
Do not quite understand.
Need an opinion @sezero?
No problem.

**Comment by sezero** [comment]
You macroized unsf into PNAME and slightly reduced the cmakefile size:
nothing worthy there.

You also changed the SOVERSION to directly into release version number:
That's a no, SOVERSION can stay the same unless api changes occur.

The only really different thing I see here is that the man page being
installed.

Overall, I don't see this PR helping with anything. (Sorry.)

**Comment by zvezdochiot** [comment]
Hmm. I changed SOVERSION to VERSION_MAJOR (= 1). Why in one CMakeFiles.txt several combinations of versions? So you can get confused.

Find a way to create links in /usr/lib in this confusion? This is a kind of perversion.

**Comment by psi29a** [comment]
application version is the same as library version, one is for application and the other is for ABI compatibility.  If there is no change in ABI, then no reason to bump the SOVERSION.

**Comment by zvezdochiot** [comment]
VERSION_MAJOR=1
VERSION_MINOR=1
VERSION_RELEASE=0
UNSF_VERSION="${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_RELEASE}"=1.1.0
SOVERSION=1
VERSION=1.1.0

What is superfluous here? After all, something is just superfluous.

**Comment by psi29a** [comment]
Don't understand why you need to set PNAME... it's not like the name of the project changes very often, if at all.

Things like this:
```
-SET_TARGET_PROPERTIES(libunsf_dynamic PROPERTIES
-    SOVERSION ${SOVERSION}
-    VERSION ${VERSION}
-    OUTPUT_NAME ${LIBRARY_DYN_NAME} CLEAN_DIRECT_OUTPUT 1
+SET_TARGET_PROPERTIES(lib${PNAME}_dynamic PROPERTIES
+    SOVERSION ${VERSION_MAJOR}
+    VERSION ${UNSF_VERSION}
+    OUTPUT_NAME ${PNAME} CLEAN_DIRECT_OUTPUT 1
```

We keep the SOVERSION seperate from VERSION, one is for ABI and other is for application/library.

**Comment by zvezdochiot** [comment]
In this particular case:
SOVERSION = VERSION_MAJOR
VERSION = UNSF_VERSION
This is an obvious dubbing.

I use the PNAME to create a template from this CMakeLists.txt.

**Pull request closed without merging**
