### PR TITLE
fix problem where windows forbids certain letters to used in filenames

### LINKED ISSUE #12: windows builds can't handle '<' in file names
With ftp://ftp.personalcopy.net/pub/PCLite.sfArk.exe  :

....>unsf PCLite.sf2
Reading PCLite.sf2
Writing out to: ./
Opened ./PCLite.cfg for writing.

Could not open patch file ./PCLite-B0/<amac-OvdG.pat

Could not open patch file ./PCLite-B0/<amac-DistG.pat
Finished!

### PR DESCRIPTION
**Pull request by psi29a**
This should resolve https://github.com/psi29a/unsf/issues/12

### CODE REVIEW

**Comment by psi29a** [comment]
@sezero workf for you?

**Comment by sezero** [comment]
No errors. I thought that you thought of '_', but the '<' character is mysteriously translated into 'L', curious: any reason?

**Comment by psi29a** [comment]
Take a look at the code and you'll see why.

**Comment by sezero** [comment]
Well, the result looks confusing: it looks more like an intended name rather than a translated one, and _possibly_ has more chance to clash with another.

**Comment by psi29a** [comment]
Which way do you think is best? There is a none-zero chance of clashes either way I think.

> The ASCII character field achSampleName contains the name of the sample expressed in ASCII, with unused terminal characters filled with zero valued bytes. Sample names are case-sensitive. A unique name should always be assigned to each sample in the SoundFont compatible bank to enable identification. However, if a bank is read containing the erroneous state of samples with identical names, the samples should not be discarded. They should either be preserved as read or preferably uniquely renamed.

**Comment by psi29a** [comment]
If we really wanted to avoid clashes, rename the whole file with a guid (type4) or other unique identity.

**Comment by sezero** [comment]
Not sure.

One idea: Reallocate with +2 extra length, add a XX prefix
to the name, XX being a two-digit number increasing with every
iteration, then replace the forbidden chars with '_' or '#' or
whatever, but not something like 'L' or the like.

**Comment by sezero** [comment]
On 9/29/16, Bret Curtis notifications@github.com wrote:

> If we really wanted to avoid clashes, rename the whole file with a
> guid (type4) or other unique identity.

That's another possibility

**Comment by psi29a** [comment]
So the original code did some char changing too, but missed the < > / and :, so I added those.

It some kind of pattern of replacing forbidden chars with either ' ' (space) or '_' if it was the beginning of a pair of chars to be replaced.

It did not take into account any name collisions, so we're not going to either.

**Comment by sezero** [comment]
This is OK for me.  Tested mingw build under 32 bit winxp, the two '<' were nicely translated into '_'.

**Comment by psi29a** [comment]
Done. I tried to be clever, and it almost worked too.

```
DEBUG: \/:*?"<>|
DEBUG: SJLIMGLMY
```

This was the result, sadly ? and > were too close together, so my code give them the same value. So screw it, and go with the old method that was already there. _sigh_

I might come back to this later.

**Pull request merged**
