### PR TITLE
allocate 1MiB off the bat, then increment by a multiple of 2 which sh…

### PR DESCRIPTION
**Pull request by psi29a**
…ould cut down on memory allocations

### CODE REVIEW

**Comment by psi29a** [comment]
@sezero can you test this on your windows machine and 32-bit VMs to see if there is any reduction in time and memory pressure?

**Comment by sezero** [comment]
I tried it on my 32 bit linux, and it works.

```
Reading PC51f.sf2
Writing out to: ./
Opened ./PC51f.cfg for writing.
==5177== Warning: set address range perms: large range 134217760 (noaccess)
Finished!
==5177==
==5177== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 13 from 1)
==5177== malloc/free: in use at exit: 0 bytes in 0 blocks.
==5177== malloc/free: 2,792 allocs, 2,792 frees, 332,217,418 bytes allocated.
==5177== For counts of detected errors, rerun with: -v
==5177== All heap blocks were freed -- no leaks are possible.
```

I then tried doing the following:

```
-        if (*mem_alloced == 0) *mem_alloced = 1048576;
-        else *mem_alloced *= 2;
+        *mem_alloced += (*mem_size + 1048575) & ~1048575;
```

... so it doesn't muliply uncesessarily. Result:

```
Reading PC51f.sf2
Writing out to: ./
Opened ./PC51f.cfg for writing.
==5532== Warning: set address range perms: large range 133173280 (noaccess)
Finished!
==5532==
==5532== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 13 from 1)
==5532== malloc/free: in use at exit: 0 bytes in 0 blocks.
==5532== malloc/free: 2,784 allocs, 2,784 frees, 322,817,098 bytes allocated.
==5532== For counts of detected errors, rerun with: -v
==5532== All heap blocks were freed -- no leaks are possible.
```

... seems slightly better. Just a suggestion.

Result with 130mb fluidsynth soundfont:

```
==5781== Memcheck, a memory error detector.
==5781== Copyright (C) 2002-2007, and GNU GPL'd, by Julian Seward et al.
==5781== Using LibVEX rev 1804, a library for dynamic binary translation.
==5781== Copyright (C) 2004-2007, and GNU GPL'd, by OpenWorks LLP.
==5781== Using valgrind-3.3.0, a dynamic binary instrumentation framework.
==5781== Copyright (C) 2000-2007, and GNU GPL'd, by Julian Seward et al.
==5781== For more details, rerun with: -v
==5781==
Reading FluidR3_GM.sf2
Writing out to: ./
Opened ./FluidR3_GM.cfg for writing.
==5781== Warning: set address range perms: large range 148196112 (undefined)
==5781== Warning: set address range perms: large range 134217728 (undefined)
==5781== Warning: set address range perms: large range 133173280 (noaccess)
==5781== Warning: set address range perms: large range 267391008 (noaccess)
==5781== Warning: set address range perms: large range 148196144 (noaccess)
Finished!
==5781==
==5781== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 13 from 1)
==5781== malloc/free: in use at exit: 0 bytes in 0 blocks.
==5781== malloc/free: 8,465 allocs, 8,465 frees, 677,217,232 bytes allocated.
==5781== For counts of detected errors, rerun with: -v
==5781== All heap blocks were freed -- no leaks are possible.
```

Time results w/o valgrind:

```
$ time ./unsf PC51f.sf2
Reading PC51f.sf2
Writing out to: ./
Opened ./PC51f.cfg for writing.
Finished!

real    0m10.742s
user    0m4.731s
sys     0m0.871s
```

```
$ time ./unsf FluidR3_GM.sf2
Reading FluidR3_GM.sf2
Writing out to: ./
Opened ./FluidR3_GM.cfg for writing.
Finished!

real    1m16.540s
user    0m23.153s
sys     0m4.649s
```

It seems I f.cked my win-xp 32 bit partition badly, so can't test on it.
Will try on the win8.1-x64 shortly.

**Comment by sezero** [comment]
Conversions of both PC51f.sf2 and FluidR3_GM.sf2 complete quickly under win8.1-x64.

**Comment by psi29a** [comment]
That works better as it removes branches called every time mem_write8 is called. It pretty much what we do in write_block as well.

Anyway, I'm glad that it helps relieve some problems.

**Comment by sezero** [comment]
OK then.  I guess this can be merged and #10 can be closed.

**Comment by sezero** [comment]
BTW, I had added some initial incomplete support for soundfont to libtimidity,
see at https://github.com/sezero/libtimidity.git

Not the same thing at all, of course, but playing midi with it using PC51f.sf2
only takes about 30mb:

```
$ valgrind ./wildtimi -c PC51f.cfg hex1.mid 
==2948== Memcheck, a memory error detector.
==2948== Copyright (C) 2002-2007, and GNU GPL'd, by Julian Seward et al.
==2948== Using LibVEX rev 1804, a library for dynamic binary translation.
==2948== Copyright (C) 2004-2007, and GNU GPL'd, by OpenWorks LLP.
==2948== Using valgrind-3.3.0, a dynamic binary instrumentation framework.
==2948== Copyright (C) 2000-2007, and GNU GPL'd, by Julian Seward et al.
==2948== For more details, rerun with: -v
==2948== 

WildMidi player using libTiMidity backend

Initializing audio output system
Initializing libTiMidity v0.3.0

 +  Volume up        -  Volume down
 ,  1sec Seek Back   .  1sec Seek Forward    p  Pause On/Off
 n  Next Midi        q  Quit

Playing hex1.mid 
q       [Approx  2m 56s Total] [ 80] [ 0m  3s Processed] [ 1%] -  
Shutting down sound output

==2948== 
==2948== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 13 from 1)
==2948== malloc/free: in use at exit: 0 bytes in 0 blocks.
==2948== malloc/free: 9,286 allocs, 9,286 frees, 37,754,027 bytes allocated.
==2948== For counts of detected errors, rerun with: -v
==2948== All heap blocks were freed -- no leaks are possible.
```

You may still tweak more I think.

**Comment by psi29a** [comment]
Nice ;)

We could always piggy back off fluidsynth? It has better support for SF than timidity from what I read.

**Comment by sezero** [comment]
I'd rather prefer something small and independent:  unsf is such an app/lib and it should live as is  (If you meant wildmidi using fluidsynth: same argument from me.)

**Pull request merged**
